// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SparkEquation.Trial.WebAPI.Data;

namespace SparkEquation.Trial.WebAPI.Data.Migrations
{
    [DbContext(typeof(MainDbContext))]
    partial class MainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("SparkEquation.Trial.WebAPI.Data.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Country");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Brand");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "USA",
                            Name = "Pepsi"
                        },
                        new
                        {
                            Id = 2,
                            Country = "USA",
                            Name = "Coca Cola"
                        },
                        new
                        {
                            Id = 3,
                            Country = "USA",
                            Name = "Bud"
                        },
                        new
                        {
                            Id = 4,
                            Country = "France",
                            Name = "Bordeaux"
                        },
                        new
                        {
                            Id = 5,
                            Country = "Russia",
                            Name = "Essentuki"
                        },
                        new
                        {
                            Id = 6,
                            Country = "Russia",
                            Name = "Lada"
                        },
                        new
                        {
                            Id = 7,
                            Country = "USA",
                            Name = "Chevrolet"
                        },
                        new
                        {
                            Id = 8,
                            Country = "Japan",
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 9,
                            Country = "Japan",
                            Name = "Nissan"
                        });
                });

            modelBuilder.Entity("SparkEquation.Trial.WebAPI.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Drinks"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Alcohol"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sparkling"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cars"
                        },
                        new
                        {
                            Id = 5,
                            Name = "4x4"
                        });
                });

            modelBuilder.Entity("SparkEquation.Trial.WebAPI.Data.Models.CategoryProduct", b =>
                {
                    b.Property<int>("CategoryId");

                    b.Property<int>("ProductId");

                    b.HasKey("CategoryId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("CategoryProducts");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 2
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 3
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 4
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 5
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 6
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 7
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 8
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 9
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 10
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 11
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 12
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 13
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 1
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 2
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 9
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 10
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductId = 3
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductId = 4
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductId = 5
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductId = 6
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductId = 7
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductId = 8
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductId = 9
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductId = 10
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductId = 12
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 14
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 15
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 16
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 17
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 18
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 19
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 20
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 21
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 22
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 23
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 24
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 25
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 26
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 27
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 28
                        },
                        new
                        {
                            CategoryId = 5,
                            ProductId = 14
                        },
                        new
                        {
                            CategoryId = 5,
                            ProductId = 21
                        },
                        new
                        {
                            CategoryId = 5,
                            ProductId = 23
                        },
                        new
                        {
                            CategoryId = 5,
                            ProductId = 26
                        });
                });

            modelBuilder.Entity("SparkEquation.Trial.WebAPI.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BrandId");

                    b.Property<DateTime?>("ExpirationDate");

                    b.Property<bool>("Featured");

                    b.Property<int>("ItemsInStock");

                    b.Property<string>("Name");

                    b.Property<double>("Rating");

                    b.Property<DateTime?>("ReceiptDate");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 4,
                            Featured = false,
                            ItemsInStock = 0,
                            Name = "La Vieille Ferme Rouge",
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 4,
                            Featured = false,
                            ItemsInStock = 0,
                            Name = "J.P. Chenet Pays D'Oc Cabernet - Syrah",
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 5,
                            Featured = false,
                            ItemsInStock = 0,
                            Name = "Essentuki 4",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 5,
                            Featured = false,
                            ItemsInStock = 0,
                            Name = "Essentuki 17",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 2,
                            Featured = false,
                            ItemsInStock = 0,
                            Name = "Fanta",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 2,
                            Featured = false,
                            ItemsInStock = 0,
                            Name = "Coca Cola",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 2,
                            Featured = false,
                            ItemsInStock = 0,
                            Name = "Sprite",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 1,
                            Featured = false,
                            ItemsInStock = 0,
                            Name = "Pepsi",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 3,
                            Featured = false,
                            ItemsInStock = 0,
                            Name = "Budweiser",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 3,
                            Featured = false,
                            ItemsInStock = 0,
                            Name = "Budweiser 66",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 2,
                            Featured = false,
                            ItemsInStock = 0,
                            Name = "Simply",
                            Rating = 3.0
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 2,
                            Featured = false,
                            ItemsInStock = 0,
                            Name = "Surge",
                            Rating = 3.6000000000000001
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 2,
                            Featured = false,
                            ItemsInStock = 0,
                            Name = "Zico",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 6,
                            Featured = false,
                            ItemsInStock = 0,
                            Name = "Niva",
                            Rating = 3.5
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 6,
                            Featured = false,
                            ItemsInStock = 0,
                            Name = "1200/1300",
                            Rating = 1.5
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 6,
                            Featured = false,
                            ItemsInStock = 0,
                            Name = "1500",
                            Rating = 1.8
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 6,
                            Featured = false,
                            ItemsInStock = 0,
                            Name = "1600",
                            Rating = 2.0
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 6,
                            Featured = false,
                            ItemsInStock = 0,
                            Name = "Oka",
                            Rating = 1.0
                        },
                        new
                        {
                            Id = 19,
                            BrandId = 6,
                            Featured = false,
                            ItemsInStock = 0,
                            Name = "Kalina",
                            Rating = 3.0
                        },
                        new
                        {
                            Id = 20,
                            BrandId = 6,
                            Featured = false,
                            ItemsInStock = 0,
                            Name = "Granta",
                            Rating = 3.2000000000000002
                        },
                        new
                        {
                            Id = 21,
                            BrandId = 6,
                            Featured = false,
                            ItemsInStock = 0,
                            Name = "Taiga",
                            Rating = 3.7999999999999998
                        },
                        new
                        {
                            Id = 22,
                            BrandId = 6,
                            Featured = false,
                            ItemsInStock = 0,
                            Name = "Priora",
                            Rating = 3.2000000000000002
                        },
                        new
                        {
                            Id = 23,
                            BrandId = 7,
                            Featured = false,
                            ItemsInStock = 0,
                            Name = "Tahoe",
                            Rating = 4.2000000000000002
                        },
                        new
                        {
                            Id = 24,
                            BrandId = 7,
                            Featured = false,
                            ItemsInStock = 0,
                            Name = "Camaro",
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 25,
                            BrandId = 7,
                            Featured = false,
                            ItemsInStock = 0,
                            Name = "Corvette",
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 26,
                            BrandId = 8,
                            Featured = false,
                            ItemsInStock = 0,
                            Name = "Land Cruiser",
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 27,
                            BrandId = 8,
                            Featured = false,
                            ItemsInStock = 0,
                            Name = "Prius",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 28,
                            BrandId = 9,
                            Featured = false,
                            ItemsInStock = 0,
                            Name = "Maxima",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 29,
                            BrandId = 9,
                            Featured = false,
                            ItemsInStock = 0,
                            Name = "Cube",
                            Rating = 4.5
                        });
                });

            modelBuilder.Entity("SparkEquation.Trial.WebAPI.Data.Models.CategoryProduct", b =>
                {
                    b.HasOne("SparkEquation.Trial.WebAPI.Data.Models.Category", "Category")
                        .WithMany("CategoryProducts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SparkEquation.Trial.WebAPI.Data.Models.Product", "Product")
                        .WithMany("CategoryProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SparkEquation.Trial.WebAPI.Data.Models.Product", b =>
                {
                    b.HasOne("SparkEquation.Trial.WebAPI.Data.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
